### ISSUE TITLE
ModuleNotFoundError: No module named 'exp_configs'

### ISSUE THREAD

**Issue by n-hafidi** [smounsav/bilevel_augment_histo#1]
Thank you for sharing the source code for this valuable contribution!

I'm encountering an issue while attempting to execute the trainval.py script from your project. It's throwing a ModuleNotFoundError: No module named 'exp_configs' error.

Error Output:

arduino

Traceback (most recent call last):
  File "/content/drive/MyDrive/bilevel_augment_histo-main/trainval.py", line 10, in <module>
    import exp_configs
ModuleNotFoundError: No module named 'exp_configs'

I thoroughly reviewed the project's codebase to locate the 'exp_configs' module, but I couldn't find any file or module bearing that name. It appears that the script is attempting to import a module that isn't present in the project.

**Comment by smounsav** [comment]
Hello,
to solve this, you have to install haven-ai (https://github.com/haven-ai/haven-ai). This is the experiment manager we used in this project.
