### ISSUE TITLE
Package versions have conflicting dependencies

### ISSUE THREAD

**Issue by n-hafidi** [smounsav/bilevel_augment_histo#2]
Unfortunately, there many other problems, linked to the package versions have conflicting dependencies!
While I'm trying to install modules in requirements
that's tell me that : 
The conflict is caused by:
    torchmeta 1.8.0 depends on torch<1.10.0 and >=1.4.0
    torchmeta 1.7.0 depends on torch<1.9.0 and >=1.4.0
    torchmeta 1.6.1 depends on torch<1.8.0 and >=1.4.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

'torchemeta' is not compatible with any of the version of 'torch', used in your project, i don't know who did you do to run the project !

**Comment by smounsav** [comment]
Torch-meta is a package I'm importing. I can't change the dependencies it requires.
To solve this, I recommend to create a virtual environment with a Pytorch version allowed by your system and corresponding to torch-meta requirements.
